/**
 * OAuth 2.0 PKCE helpers for Spotify user authentication.
 *
 * Spotify's Authorization Code with PKCE flow is the recommended approach
 * for user-facing auth in apps that cannot securely store a client secret
 * on the client side (SPAs, mobile apps). We use it here for accessing
 * user library data (saved albums).
 *
 * @see https://developer.spotify.com/documentation/web-api/tutorials/code-pkce-flow
 */

import { createHash, randomBytes } from 'crypto';
import type { SpotifyTokenResponse } from './types';

// ---------------------------------------------------------------------------
// PKCE helpers
// ---------------------------------------------------------------------------

/**
 * Generate a cryptographically random PKCE code verifier and its
 * corresponding S256 challenge.
 *
 * The verifier is a 64-character URL-safe random string. The challenge is
 * the Base64-URL-encoded SHA-256 hash of the verifier.
 */
export function generatePKCE(): { verifier: string; challenge: string } {
  const verifier = randomBytes(48).toString('base64url').slice(0, 128);

  const hash = createHash('sha256').update(verifier).digest();
  const challenge = hash
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');

  return { verifier, challenge };
}

// ---------------------------------------------------------------------------
// Authorize URL
// ---------------------------------------------------------------------------

/**
 * Build the Spotify authorization URL that the user should be redirected to.
 *
 * @param state  Opaque CSRF token to validate on callback.
 * @param codeChallenge  PKCE S256 challenge generated by `generatePKCE()`.
 */
export function getSpotifyAuthUrl(state: string, codeChallenge: string): string {
  const clientId = process.env.SPOTIFY_CLIENT_ID;
  if (!clientId) {
    throw new Error(
      'SPOTIFY_CLIENT_ID is not set. Please add it to your environment variables.',
    );
  }

  const redirectUri = `${process.env.BETTER_AUTH_URL}/api/spotify/callback`;
  if (!process.env.BETTER_AUTH_URL) {
    throw new Error(
      'BETTER_AUTH_URL is not set. Please add it to your environment variables.',
    );
  }

  const params = new URLSearchParams({
    response_type: 'code',
    client_id: clientId,
    scope: 'user-library-read user-read-private user-top-read',
    redirect_uri: redirectUri,
    state,
    code_challenge_method: 'S256',
    code_challenge: codeChallenge,
  });

  return `https://accounts.spotify.com/authorize?${params.toString()}`;
}

// ---------------------------------------------------------------------------
// Token exchange
// ---------------------------------------------------------------------------

/**
 * Exchange an authorization code for access and refresh tokens.
 *
 * @param code          The authorization code received on the callback.
 * @param codeVerifier  The original PKCE code verifier (stored in session).
 */
export async function exchangeSpotifyCode(
  code: string,
  codeVerifier: string,
): Promise<SpotifyTokenResponse> {
  const clientId = process.env.SPOTIFY_CLIENT_ID;
  if (!clientId) {
    throw new Error(
      'SPOTIFY_CLIENT_ID is not set. Please add it to your environment variables.',
    );
  }

  const redirectUri = `${process.env.BETTER_AUTH_URL}/api/spotify/callback`;

  const response = await fetch('https://accounts.spotify.com/api/token', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: new URLSearchParams({
      grant_type: 'authorization_code',
      code,
      redirect_uri: redirectUri,
      client_id: clientId,
      code_verifier: codeVerifier,
    }).toString(),
  });

  if (!response.ok) {
    const body = await response.text().catch(() => '');
    throw new Error(
      `Spotify code exchange failed: ${response.status} ${response.statusText}${body ? ` — ${body}` : ''}`,
    );
  }

  return (await response.json()) as SpotifyTokenResponse;
}

// ---------------------------------------------------------------------------
// Token refresh
// ---------------------------------------------------------------------------

/**
 * Refresh an expired user access token using a refresh token.
 *
 * @param refreshToken  The refresh token obtained during the initial exchange.
 */
export async function refreshSpotifyToken(
  refreshToken: string,
): Promise<SpotifyTokenResponse> {
  const clientId = process.env.SPOTIFY_CLIENT_ID;
  if (!clientId) {
    throw new Error(
      'SPOTIFY_CLIENT_ID is not set. Please add it to your environment variables.',
    );
  }

  const response = await fetch('https://accounts.spotify.com/api/token', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: new URLSearchParams({
      grant_type: 'refresh_token',
      refresh_token: refreshToken,
      client_id: clientId,
    }).toString(),
  });

  if (!response.ok) {
    const body = await response.text().catch(() => '');
    throw new Error(
      `Spotify token refresh failed: ${response.status} ${response.statusText}${body ? ` — ${body}` : ''}`,
    );
  }

  return (await response.json()) as SpotifyTokenResponse;
}
